apiVersion: v1
kind: ConfigMap
metadata: {name: pios-config, namespace: pios}
data:
  PIOS_ENV: production
  PIOS_API_PREFIX: /api/v1
  PIOS_AUTH_MODE: oidc
  PIOS_ALLOW_DEV_TOKENS: "false"
  PIOS_ORGANIZATION_CODE: NBC
  PIOS_DEFAULT_SITE_CODE: TGH
  PIOS_CORS_ORIGINS: https://pios.example.sa
  PIOS_OBJECT_STORAGE_BACKEND: s3
  PIOS_EXPORT_STORAGE_ROOT: /app/var/exports
