"""Sprint 10 production governance, privacy and release provenance."""
from alembic import op
revision='0010_sprint10_production_governance';down_revision='0009_sprint9_intelligence_ai_governance';branch_labels=None;depends_on=None
def upgrade():
  for sql in [
  "CREATE TABLE IF NOT EXISTS release_packages (id UUID PRIMARY KEY,organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,code VARCHAR(64) NOT NULL,version VARCHAR(32) NOT NULL,release_sha VARCHAR(64) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'Draft',artifact_count INTEGER NOT NULL DEFAULT 0,evaluation_json JSONB NOT NULL DEFAULT '{}'::jsonb,created_by UUID REFERENCES users(id) ON DELETE SET NULL,approved_by UUID REFERENCES users(id) ON DELETE SET NULL,approved_at TIMESTAMPTZ,published_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),row_version INTEGER NOT NULL DEFAULT 1,CONSTRAINT uq_release_org_code UNIQUE(organization_id,code))",
  "CREATE INDEX IF NOT EXISTS ix_release_package_org_status_created ON release_packages(organization_id,status,created_at)",
  "CREATE TABLE IF NOT EXISTS release_artifacts (id UUID PRIMARY KEY,release_package_id UUID NOT NULL REFERENCES release_packages(id) ON DELETE CASCADE,name VARCHAR(255) NOT NULL,artifact_type VARCHAR(64) NOT NULL,uri TEXT NOT NULL,sha256 VARCHAR(64) NOT NULL,size_bytes BIGINT NOT NULL DEFAULT 0,media_type VARCHAR(128),signed BOOLEAN NOT NULL DEFAULT FALSE,signature_reference TEXT,immutable BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),row_version INTEGER NOT NULL DEFAULT 1,CONSTRAINT uq_release_artifact_name UNIQUE(release_package_id,name))",
  "CREATE INDEX IF NOT EXISTS ix_release_artifact_package_type ON release_artifacts(release_package_id,artifact_type)",
  "CREATE TABLE IF NOT EXISTS security_control_assessments (id UUID PRIMARY KEY,organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,code VARCHAR(64) NOT NULL,title VARCHAR(255) NOT NULL,category VARCHAR(64) NOT NULL,severity VARCHAR(8) NOT NULL DEFAULT 'P1',required BOOLEAN NOT NULL DEFAULT TRUE,status VARCHAR(16) NOT NULL DEFAULT 'Pending',evidence_reference TEXT,details JSONB NOT NULL DEFAULT '{}'::jsonb,checked_by UUID REFERENCES users(id) ON DELETE SET NULL,checked_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),row_version INTEGER NOT NULL DEFAULT 1,CONSTRAINT uq_security_control_org_code UNIQUE(organization_id,code))",
  "CREATE INDEX IF NOT EXISTS ix_security_control_org_status_severity ON security_control_assessments(organization_id,status,severity)",
  "CREATE TABLE IF NOT EXISTS retention_policies (id UUID PRIMARY KEY,organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,code VARCHAR(64) NOT NULL,entity_type VARCHAR(128) NOT NULL,retention_days INTEGER NOT NULL,legal_basis TEXT NOT NULL,purge_method VARCHAR(64) NOT NULL DEFAULT 'SoftDeleteThenPurge',active BOOLEAN NOT NULL DEFAULT TRUE,approved_by UUID REFERENCES users(id) ON DELETE SET NULL,approved_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),row_version INTEGER NOT NULL DEFAULT 1,CONSTRAINT uq_retention_org_code UNIQUE(organization_id,code))",
  "CREATE TABLE IF NOT EXISTS legal_holds (id UUID PRIMARY KEY,organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,code VARCHAR(64) NOT NULL,scope_type VARCHAR(64) NOT NULL,scope_id VARCHAR(128),reason TEXT NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'Active',placed_by UUID REFERENCES users(id) ON DELETE SET NULL,placed_at TIMESTAMPTZ NOT NULL DEFAULT now(),released_by UUID REFERENCES users(id) ON DELETE SET NULL,released_at TIMESTAMPTZ,release_reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),row_version INTEGER NOT NULL DEFAULT 1,CONSTRAINT uq_legal_hold_org_code UNIQUE(organization_id,code))",
  "CREATE INDEX IF NOT EXISTS ix_legal_hold_org_status_scope ON legal_holds(organization_id,status,scope_type)",
  "CREATE TABLE IF NOT EXISTS audit_export_packages (id UUID PRIMARY KEY,organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,code VARCHAR(64) NOT NULL,period_start TIMESTAMPTZ NOT NULL,period_end TIMESTAMPTZ NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'Generated',event_count INTEGER NOT NULL DEFAULT 0,root_hash VARCHAR(64) NOT NULL,file_sha256 VARCHAR(64) NOT NULL,uri TEXT NOT NULL,manifest_json JSONB NOT NULL DEFAULT '{}'::jsonb,created_by UUID REFERENCES users(id) ON DELETE SET NULL,verified_by UUID REFERENCES users(id) ON DELETE SET NULL,verified_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),row_version INTEGER NOT NULL DEFAULT 1,CONSTRAINT uq_audit_export_org_code UNIQUE(organization_id,code))",
  "CREATE INDEX IF NOT EXISTS ix_audit_export_org_status_created ON audit_export_packages(organization_id,status,created_at)"]:
    op.execute(sql)
def downgrade():
  for t in ['audit_export_packages','legal_holds','retention_policies','security_control_assessments','release_artifacts','release_packages']:op.execute(f'DROP TABLE IF EXISTS {t} CASCADE')
