apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pios-api
  namespace: pios
spec:
  selector:
    matchLabels:
      app: pios-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
